import type { ActivityEvent, Contact, Domain, EmailMessage, Invitation, NotificationItem, TeamMember, User, UserPreferences, Workspace } from "@/types";

export const demoUser: User = {
  id: "user-01",
  name: "Alex Morgan",
  email: "alex@northstar.studio",
  avatarColor: "#6f63e8",
  role: "Owner",
};

export const demoWorkspace: Workspace = {
  id: "workspace-01",
  name: "Northstar Studio",
  domain: "northstar.studio",
  plan: "Demo",
};

export const demoPreferences: UserPreferences = {
  theme: "light",
  density: "comfortable",
  productNotifications: true,
  emailNotifications: false,
  weeklyDigest: true,
  desktopNotifications: false,
  displayName: "Alex Morgan",
  signature: "Alex Morgan\nNorthstar Studio",
  defaultSender: "alex@northstar.studio",
  replyBehavior: "reply",
};

const alex = { name: "Alex Morgan", email: "alex@northstar.studio" };

export const demoEmails: EmailMessage[] = [
  {
    id: "mail-01",
    from: { name: "Maya Chen", email: "maya@brightpaper.example" },
    to: [alex],
    subject: "The new brand direction looks wonderful",
    preview: "Thanks for sharing the updated concepts. The warm palette feels just right…",
    body: "Hi Alex,\n\nThanks for sharing the updated concepts. The warm palette feels just right for the launch, and the type pairing is especially strong.\n\nCould we take a look at the final mobile screens on Thursday? I can leave notes before our call.\n\nBest,\nMaya",
    date: "2026-10-09T09:42:00+05:30",
    folder: "inbox",
    read: false,
    starred: true,
    attachments: [{ id: "att-01", name: "brand-notes.pdf", size: "2.4 MB", type: "PDF" }],
    labels: ["Clients"],
  },
  {
    id: "mail-02",
    from: { name: "Noah Patel", email: "noah@fieldnotes.example" },
    to: [alex],
    subject: "Re: Field Notes — project timeline",
    preview: "Perfect, that gives our team enough time to get the copy polished before…",
    body: "Hi Alex,\n\nPerfect, that gives our team enough time to get the copy polished before the review. I have added the dates to our shared plan.\n\nLet's reconnect on Monday.\n\nNoah",
    date: "2026-10-09T08:16:00+05:30",
    folder: "inbox",
    read: false,
    starred: false,
    attachments: [],
    labels: ["Work"],
  },
  {
    id: "mail-03",
    from: { name: "Lena Ortiz", email: "lena@papertrail.example" },
    to: [alex],
    subject: "A few ideas for the fall newsletter",
    preview: "I pulled together a short list of stories we could feature next month. The…",
    body: "Hello Alex,\n\nI pulled together a short list of stories we could feature next month. The collection launches on October 21, so there is a nice window to introduce the makers behind it.\n\nI have attached the draft outline. Let me know what you think.\n\nLena",
    date: "2026-10-08T18:31:00+05:30",
    folder: "inbox",
    read: true,
    starred: false,
    attachments: [{ id: "att-02", name: "newsletter-outline.docx", size: "84 KB", type: "DOCX" }],
    labels: ["Updates"],
  },
  {
    id: "mail-04",
    from: { name: "Studio Calendar", email: "calendar@northstar.studio" },
    to: [alex],
    subject: "Reminder: product review tomorrow at 10:30",
    preview: "A friendly reminder that your product review is scheduled for tomorrow…",
    body: "Hi Alex,\n\nA friendly reminder that your product review is scheduled for tomorrow at 10:30 AM.\n\nAgenda\n• Review the latest prototype\n• Confirm handoff details\n• Agree on launch checklist\n\nSee you there!",
    date: "2026-10-08T15:04:00+05:30",
    folder: "inbox",
    read: true,
    starred: false,
    attachments: [],
    labels: ["Calendar"],
  },
  {
    id: "mail-05",
    from: { name: "Iris Kim", email: "iris@smallhours.example" },
    to: [alex],
    subject: "Your invoice for September",
    preview: "I've attached the September invoice for your records. Please let me know if…",
    body: "Hi Alex,\n\nI've attached the September invoice for your records. Please let me know if you need anything else from me.\n\nThank you,\nIris",
    date: "2026-10-07T11:20:00+05:30",
    folder: "inbox",
    read: true,
    starred: false,
    attachments: [{ id: "att-03", name: "invoice-september.pdf", size: "146 KB", type: "PDF" }],
    labels: ["Finance"],
  },
  {
    id: "mail-06",
    from: { name: "Theo Williams", email: "theo@plainspoken.example" },
    to: [alex],
    subject: "Quick question about the workshop",
    preview: "Would Friday afternoon work for a short review with the design group?…",
    body: "Hey Alex,\n\nWould Friday afternoon work for a short review with the design group? We can keep it to 25 minutes.\n\nCheers,\nTheo",
    date: "2026-10-06T16:08:00+05:30",
    folder: "inbox",
    read: true,
    starred: false,
    attachments: [],
    labels: ["Work"],
  },
  {
    id: "mail-07",
    from: { name: "Amara Nwosu", email: "amara@kindred.example" },
    to: [alex],
    subject: "Thank you for the introduction",
    preview: "It was lovely meeting you at the studio opening. I'd love to continue…",
    body: "Hi Alex,\n\nIt was lovely meeting you at the studio opening. I'd love to continue our conversation about the community project.\n\nWould you be free for coffee next week?\n\nWarmly,\nAmara",
    date: "2026-10-05T10:45:00+05:30",
    folder: "inbox",
    read: true,
    starred: true,
    attachments: [],
    labels: ["Personal"],
  },
  {
    id: "mail-08",
    from: { name: "Ravi Shah", email: "ravi@atlasworks.example" },
    to: [alex],
    subject: "Updated files are ready to review",
    preview: "The revised assets are in the shared folder now. I included a short…",
    body: "Hi Alex,\n\nThe revised assets are in the shared folder now. I included a short readme with the changes from our last round.\n\nThanks,\nRavi",
    date: "2026-10-04T13:12:00+05:30",
    folder: "inbox",
    read: true,
    starred: false,
    attachments: [],
    labels: ["Clients"],
  },
  {
    id: "mail-09",
    from: { name: "Alex Morgan", email: "alex@northstar.studio" },
    to: [{ name: "Maya Chen", email: "maya@brightpaper.example" }],
    subject: "Re: Project kickoff notes",
    preview: "I have added the key milestones and a few open questions to the notes…",
    body: "Hi Maya,\n\nI have added the key milestones and a few open questions to the notes. Looking forward to getting started.\n\nBest,\nAlex",
    date: "2026-10-08T12:20:00+05:30",
    folder: "sent",
    read: true,
    starred: false,
    attachments: [],
    labels: [],
  },
  {
    id: "mail-10",
    from: { name: "Alex Morgan", email: "alex@northstar.studio" },
    to: [{ name: "Noah Patel", email: "noah@fieldnotes.example" }],
    subject: "October product notes",
    preview: "A few thoughts before the planning session…",
    body: "Hi Noah,\n\nA few thoughts before the planning session. I will add the prototype link once it is ready.\n\nAlex",
    date: "2026-10-08T09:35:00+05:30",
    folder: "drafts",
    read: true,
    starred: false,
    attachments: [],
    labels: [],
  },
  {
    id: "mail-11",
    from: { name: "Alex Morgan", email: "alex@northstar.studio" },
    to: [{ name: "Lena Ortiz", email: "lena@papertrail.example" }],
    subject: "Portfolio preview — thank you",
    preview: "Thanks again for taking a look. Here is the updated preview…",
    body: "Thanks again for taking a look. Here is the updated preview.\n\nAlex",
    date: "2026-10-01T14:15:00+05:30",
    folder: "archive",
    read: true,
    starred: false,
    attachments: [],
    labels: [],
  },
  {
    id: "mail-12",
    from: { name: "Morgan Reed", email: "morgan@weekenddesk.example" },
    to: [alex],
    subject: "Your weekly reading list",
    preview: "A few new stories we thought you might enjoy this week…",
    body: "Hello Alex,\n\nA few new stories we thought you might enjoy this week.\n\nWeekend Desk",
    date: "2026-09-28T07:24:00+05:30",
    folder: "trash",
    read: true,
    starred: false,
    attachments: [],
    labels: [],
  },
];

const demoDns = (domain: string) => [
  { id: `${domain}-mx`, type: "MX" as const, name: "@", value: "mx.example.invalid", priority: 10, status: "pending" as const, purpose: "Illustrative inbound routing target" },
  { id: `${domain}-spf`, type: "TXT" as const, name: "@", value: '"v=spf1 include:mail.example.invalid ~all"', status: "pending" as const, purpose: "Illustrative sender policy" },
  { id: `${domain}-dkim`, type: "CNAME" as const, name: "demo._domainkey", value: "demo-key.example.invalid", status: "pending" as const, purpose: "Illustrative signing record" },
  { id: `${domain}-dmarc`, type: "TXT" as const, name: "_dmarc", value: '"v=DMARC1; p=none; rua=mailto:dmarc@example.invalid"', status: "pending" as const, purpose: "Illustrative reporting policy" },
];

export const demoDomains: Domain[] = [
  {
    id: "domain-northstar",
    name: "northstar.studio",
    status: "verified",
    dnsStatus: "complete",
    provider: "Cloudflare",
    createdAt: "2026-08-14T09:00:00+05:30",
    mailboxCount: 3,
    identities: ["alex@northstar.studio", "hello@northstar.studio", "studio@northstar.studio"],
    records: demoDns("northstar.studio").map((record) => ({ ...record, status: "verified" as const })),
  },
  {
    id: "domain-atelier",
    name: "atelier.example",
    status: "pending",
    dnsStatus: "partial",
    provider: "Cloudflare",
    createdAt: "2026-10-02T14:30:00+05:30",
    mailboxCount: 1,
    identities: ["hello@atelier.example"],
    records: demoDns("atelier.example").map((record, index) => ({ ...record, status: index === 0 ? "verified" as const : "pending" as const })),
  },
];

export const demoContacts: Contact[] = [
  { id: "contact-01", name: "Maya Chen", email: "maya@brightpaper.example", company: "Bright Paper Co.", tags: ["Client", "Design"], notes: "Brand direction review on Thursday.", createdAt: "2026-09-18T09:00:00+05:30" },
  { id: "contact-02", name: "Noah Patel", email: "noah@fieldnotes.example", company: "Field Notes", tags: ["Partner"], notes: "Prefers a short agenda before calls.", createdAt: "2026-09-21T11:15:00+05:30" },
  { id: "contact-03", name: "Lena Ortiz", email: "lena@papertrail.example", company: "Papertrail Press", tags: ["Press", "Newsletter"], notes: "Planning a fall editorial feature.", createdAt: "2026-09-26T12:20:00+05:30" },
  { id: "contact-04", name: "Theo Williams", email: "theo@plainspoken.example", company: "Plainspoken Studio", tags: ["Design"], notes: "Workshop contact.", createdAt: "2026-10-01T15:45:00+05:30" },
  { id: "contact-05", name: "Iris Kim", email: "iris@smallhours.example", company: "Small Hours", tags: ["Finance"], notes: "Monthly invoices.", createdAt: "2026-10-03T08:30:00+05:30" },
];

export const demoNotifications: NotificationItem[] = [
  { id: "notice-01", title: "Domain check complete", description: "northstar.studio is ready in this demo workspace.", date: "2026-10-09T08:58:00+05:30", read: false, kind: "domain" },
  { id: "notice-02", title: "New message from Maya Chen", description: "The new brand direction looks wonderful.", date: "2026-10-09T09:42:00+05:30", read: false, kind: "message" },
  { id: "notice-03", title: "Welcome to Mailflare", description: "Your sample workspace is ready to explore.", date: "2026-10-07T10:00:00+05:30", read: true, kind: "account" },
];

export const demoActivity: ActivityEvent[] = [
  { id: "event-01", title: "Received a message", description: "Maya Chen sent “The new brand direction looks wonderful”.", date: "2026-10-09T09:42:00+05:30", actor: "You", kind: "email" },
  { id: "event-02", title: "Domain status checked", description: "northstar.studio is marked ready in demo mode.", date: "2026-10-09T08:58:00+05:30", actor: "Mailflare demo", kind: "domain" },
  { id: "event-03", title: "Contact added", description: "Iris Kim was added to your contacts.", date: "2026-10-08T16:10:00+05:30", actor: "Alex Morgan", kind: "contact" },
  { id: "event-04", title: "Draft saved", description: "October product notes was saved as a draft.", date: "2026-10-08T09:35:00+05:30", actor: "Alex Morgan", kind: "email" },
  { id: "event-05", title: "Workspace created", description: "Northstar Studio is your active workspace.", date: "2026-10-07T10:00:00+05:30", actor: "Alex Morgan", kind: "account" },
];

export const demoTeamMembers: TeamMember[] = [
  { id: "member-01", name: "Alex Morgan", email: "alex@northstar.studio", role: "Owner", status: "active", lastActive: "Just now" },
  { id: "member-02", name: "Jordan Lee", email: "jordan@northstar.studio", role: "Admin", status: "active", lastActive: "2 hours ago" },
  { id: "member-03", name: "Sam Rivera", email: "sam@northstar.studio", role: "Member", status: "active", lastActive: "Yesterday" },
];

export const demoInvitations: Invitation[] = [
  { id: "invite-01", email: "taylor@northstar.studio", role: "Member", sentAt: "2026-10-06T10:20:00+05:30", status: "pending" },
];
