import Link from "next/link";
import { ArrowDown, ArrowRight, ArrowUpRight, AtSign, BarChart3, Check, ChevronDown, CircleCheck, ContactRound, Globe2, Inbox, LockKeyhole, Mail, MousePointer2, ShieldCheck, Sparkles, Workflow, Zap } from "lucide-react";
import { Brand } from "@/components/layout/brand";
import { buttonVariants } from "@/components/ui/button";
import { cn } from "@/lib/utils";

const featureItems = [
  { icon: Globe2, title: "Domains at a glance", text: "See which domains are set up, which need a check, and where to continue." },
  { icon: Inbox, title: "A calmer inbox", text: "Keep messages, drafts, stars, archive, and trash in one focused workspace." },
  { icon: Workflow, title: "Provider-aware setup", text: "Follow a clear checklist while keeping real DNS values tied to your mail provider." },
  { icon: ContactRound, title: "People, not just addresses", text: "Keep contacts, tags, and helpful context close to your conversations." },
  { icon: BarChart3, title: "Useful workspace signals", text: "Explore activity trends without mistaking demo metrics for delivery analytics." },
  { icon: ShieldCheck, title: "Clear integration boundaries", text: "Understand what belongs to your setup and what this frontend preview does not do." },
];

export function LandingPage() {
  return (
    <main className="overflow-hidden bg-background">
      <div className="marketing-grid pointer-events-none absolute inset-x-0 top-0 h-[760px] opacity-90" />
      <header className="relative z-20 mx-auto flex max-w-[1240px] items-center justify-between px-5 py-5 sm:px-8 lg:px-10">
        <Brand />
        <nav aria-label="Main navigation" className="hidden items-center gap-7 md:flex"><a href="#features" className="text-xs font-medium text-muted-foreground transition hover:text-foreground">Features</a><a href="#workflow" className="text-xs font-medium text-muted-foreground transition hover:text-foreground">How it works</a><a href="#faq" className="text-xs font-medium text-muted-foreground transition hover:text-foreground">FAQ</a></nav>
        <div className="flex items-center gap-2"><Link href="/login" className="hidden rounded-lg px-3 py-2 text-xs font-semibold text-muted-foreground transition hover:text-foreground sm:inline-flex">Sign in</Link><Link href="/app" className={cn(buttonVariants({ size: "sm" }), "rounded-lg px-3.5")}>Explore demo<ArrowRight className="h-3.5 w-3.5" /></Link></div>
      </header>

      <section className="relative mx-auto grid max-w-[1240px] items-center gap-12 px-5 pb-16 pt-12 sm:px-8 md:pt-16 lg:grid-cols-[.95fr_1.05fr] lg:gap-14 lg:px-10 lg:pb-28 lg:pt-20">
        <div className="relative z-10 max-w-[540px]">
          <div className="inline-flex items-center gap-2 rounded-full border border-primary/15 bg-card/80 px-3 py-1.5 text-[10px] font-semibold text-primary shadow-sm"><span className="relative flex h-2 w-2"><span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-primary opacity-20" /><span className="relative inline-flex h-2 w-2 rounded-full bg-primary" /></span>Email for the domains you own <ArrowRight className="h-3 w-3" /></div>
          <h1 className="mt-6 text-balance text-[42px] font-semibold leading-[1.04] tracking-[-.06em] sm:text-[54px] lg:text-[64px]">Your domain’s email, <span className="bg-gradient-to-r from-primary to-violet-400 bg-clip-text text-transparent">all in one place.</span></h1>
          <p className="mt-6 max-w-[480px] text-[15px] leading-7 text-muted-foreground">Manage custom-domain inboxes, organize conversations, and follow a clear setup flow—without the clutter of a tool built for someone else’s domain.</p>
          <div className="mt-8 flex flex-wrap items-center gap-3"><Link href="/app" className={cn(buttonVariants({ size: "lg" }), "shadow-soft")}>Explore the demo<ArrowRight className="h-4 w-4" /></Link><a href="#workflow" className={cn(buttonVariants({ variant: "secondary", size: "lg" }))}><span className="flex h-6 w-6 items-center justify-center rounded-full bg-muted"><MousePointer2 className="h-3 w-3" /></span>See how it works</a></div>
          <div className="mt-7 flex flex-wrap gap-x-5 gap-y-2 text-[10px] text-muted-foreground"><span className="inline-flex items-center gap-1.5"><Check className="h-3 w-3 text-emerald-600" />Open-source inspiration</span><span className="inline-flex items-center gap-1.5"><Check className="h-3 w-3 text-emerald-600" />Frontend-only preview</span><span className="inline-flex items-center gap-1.5"><Check className="h-3 w-3 text-emerald-600" />No mail is sent</span></div>
        </div>
        <ProductPreview />
      </section>

      <section className="border-y border-border bg-card/65">
        <div className="mx-auto grid max-w-[1240px] grid-cols-2 gap-5 px-5 py-7 sm:grid-cols-4 sm:px-8 lg:px-10"><TrustItem icon={Globe2} title="Your domains" detail="bring your own" /><TrustItem icon={Inbox} title="Inbox tools" detail="keep work together" /><TrustItem icon={Workflow} title="Setup guide" detail="clear, provider-aware" /><TrustItem icon={Sparkles} title="Demo mode" detail="safe to explore" /></div>
      </section>

      <section id="features" className="relative mx-auto max-w-[1240px] px-5 py-20 sm:px-8 lg:px-10 lg:py-28">
        <div className="mx-auto max-w-[650px] text-center"><p className="text-[10px] font-bold uppercase tracking-[.15em] text-primary">A simpler workspace</p><h2 className="mt-4 text-balance text-[34px] font-semibold leading-tight tracking-[-.05em] sm:text-[43px]">The everyday essentials, designed around your domain.</h2><p className="mt-4 text-sm leading-7 text-muted-foreground">Start with the things that make custom-domain email easier to understand and maintain.</p></div>
        <div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{featureItems.map(({ icon: Icon, title, text }, index) => <div key={title} className="group rounded-2xl border border-border bg-card p-5 shadow-card transition hover:-translate-y-0.5 hover:border-primary/20 hover:shadow-soft sm:p-6"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary/10 text-primary transition group-hover:bg-primary group-hover:text-white"><Icon className="h-[18px] w-[18px]" /></span><h3 className="mt-5 text-sm font-semibold tracking-[-.02em]">{title}</h3><p className="mt-2 text-xs leading-6 text-muted-foreground">{text}</p><span className="mt-5 block text-[9px] font-semibold uppercase tracking-[.12em] text-muted-foreground/70">0{index + 1}</span></div>)}</div>
      </section>

      <section id="workflow" className="bg-[#181b2b] text-white">
        <div className="mx-auto grid max-w-[1240px] gap-12 px-5 py-20 sm:px-8 lg:grid-cols-[.85fr_1.15fr] lg:items-center lg:px-10 lg:py-24">
          <div><p className="text-[10px] font-bold uppercase tracking-[.15em] text-violet-300">Thoughtful setup</p><h2 className="mt-4 text-balance text-[35px] font-semibold leading-tight tracking-[-.05em] sm:text-[44px]">A clear route from domain to inbox.</h2><p className="mt-4 max-w-lg text-sm leading-7 text-slate-300">Mailflare is built around custom domains and Cloudflare Email Routing, with support for other sending and receiving providers. In a real setup, DNS values come from the service you choose—there is no one-size-fits-all record.</p><Link href="/app/domains" className="mt-7 inline-flex h-10 items-center gap-2 rounded-xl bg-white px-4 text-xs font-semibold text-[#171a2b] transition hover:bg-violet-50">Preview domain setup<ArrowRight className="h-3.5 w-3.5" /></Link><p className="mt-4 text-[10px] leading-5 text-slate-400">This local preview uses nonfunctional <code>example.invalid</code> values and never contacts Cloudflare or a DNS resolver.</p></div>
          <div className="relative space-y-3">{[{ number: "01", title: "Add a domain", detail: "Choose a domain you control and the provider that fits your setup.", icon: Globe2 }, { number: "02", title: "Review the provider’s records", detail: "Use the exact MX and sender-authentication values supplied for your configuration.", icon: Workflow }, { number: "03", title: "Set up identities", detail: "Create mailbox identities and organize conversations in one workspace.", icon: AtSign }, { number: "04", title: "Verify with your provider", detail: "Confirm the real DNS and mail status in the service that manages it.", icon: CircleCheck }].map((item, index) => <div key={item.number} className="flex gap-4 rounded-2xl border border-white/10 bg-white/[.045] p-4 sm:p-5"><span className="mt-0.5 text-[10px] font-bold tracking-[.12em] text-violet-300">{item.number}</span><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-white/10 text-violet-200"><item.icon className="h-4 w-4" /></span><div className="min-w-0 flex-1"><h3 className="text-xs font-semibold">{item.title}</h3><p className="mt-1.5 text-[11px] leading-5 text-slate-300">{item.detail}</p></div>{index < 3 && <ArrowDown className="mt-2 hidden h-4 w-4 text-violet-300/70 sm:block" />}</div>)}</div>
        </div>
      </section>

      <section className="mx-auto grid max-w-[1240px] gap-5 px-5 py-20 sm:px-8 lg:grid-cols-2 lg:px-10 lg:py-24">
        <div className="rounded-3xl border border-border bg-card p-6 shadow-card sm:p-8"><div className="flex items-center justify-between"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-sky-500/10 text-sky-600"><Inbox className="h-5 w-5" /></span><BadgeLike>INBOX</BadgeLike></div><h2 className="mt-6 text-[26px] font-semibold tracking-[-.04em]">Stay close to the conversations that matter.</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">Search, star, archive, and sort messages. Keep a clear line between received mail and messages you’ve drafted in the demo.</p><div className="mt-6 space-y-2.5">{["A unified inbox for custom-domain identities", "Simple organization: stars, labels, archive, trash", "Contacts and activity in the same workspace"].map((item) => <p key={item} className="flex items-start gap-2 text-xs text-muted-foreground"><Check className="mt-0.5 h-3.5 w-3.5 shrink-0 text-emerald-600" />{item}</p>)}</div><Link href="/app/inbox" className="mt-7 inline-flex items-center gap-1 text-xs font-semibold text-primary">Explore the inbox<ArrowRight className="h-3.5 w-3.5" /></Link></div>
        <div className="rounded-3xl border border-border bg-card p-6 shadow-card sm:p-8"><div className="flex items-center justify-between"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-emerald-500/10 text-emerald-600"><LockKeyhole className="h-5 w-5" /></span><BadgeLike>BUILT FOR CLARITY</BadgeLike></div><h2 className="mt-6 text-[26px] font-semibold tracking-[-.04em]">A setup guide that tells you what it is—and isn’t.</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">See illustrative DNS examples beside clear explanations. In a real integration, provider values and verified status should come from your connected backend.</p><div className="mt-6 rounded-xl border border-amber-500/20 bg-amber-500/[.06] p-3.5"><p className="flex gap-2 text-xs font-semibold"><ShieldCheck className="h-4 w-4 shrink-0 text-amber-600" />Demo boundary</p><p className="mt-1.5 text-[11px] leading-5 text-muted-foreground">Nothing here sends mail, verifies DNS, or promises security or delivery. It is a frontend prototype only.</p></div><Link href="/app/domains" className="mt-6 inline-flex items-center gap-1 text-xs font-semibold text-primary">Preview domain management<ArrowRight className="h-3.5 w-3.5" /></Link></div>
      </section>

      <section id="faq" className="border-y border-border bg-card/65">
        <div className="mx-auto grid max-w-[1240px] gap-10 px-5 py-20 sm:px-8 lg:grid-cols-[.7fr_1.3fr] lg:px-10 lg:py-24">
          <div><p className="text-[10px] font-bold uppercase tracking-[.15em] text-primary">Questions, answered</p><h2 className="mt-4 text-[34px] font-semibold leading-tight tracking-[-.05em]">Before you explore.</h2><p className="mt-4 text-sm leading-6 text-muted-foreground">A few helpful details about Mailflare and this demo build.</p><Link href="https://github.com/hieunc229/mailflare" target="_blank" rel="noreferrer" className="mt-5 inline-flex items-center gap-1 text-xs font-semibold text-primary">View the open-source project<ArrowUpRight className="h-3.5 w-3.5" /></Link></div>
          <div className="divide-y divide-border">{[
            { q: "What is Mailflare?", a: "Mailflare is an open-source, self-hosted inbox for custom domains. Its project describes integrations with Cloudflare and other mail providers, plus inbox, mailbox, contact, and organization tools." },
            { q: "Does this page send or receive email?", a: "No. This frontend-only preview uses fictional messages and local UI state. Sending only adds a demo item to Sent; nothing leaves your browser." },
            { q: "Are the DNS records usable?", a: "No. The values in this demo are explicitly illustrative and use the reserved example.invalid domain. Real values vary by provider and configuration." },
            { q: "Is sign-in real?", a: "No. Login and registration are simulated frontend flows. Do not enter a real password. The UI does not connect to an identity provider." },
            { q: "Where can I learn about setup?", a: "Use the original Mailflare documentation and current documentation for your DNS and email providers. Configuration options and provider requirements can change." },
          ].map((item) => <details key={item.q} className="group py-4"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 text-sm font-semibold marker:hidden focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><span>{item.q}</span><ChevronDown className="h-4 w-4 shrink-0 text-muted-foreground transition-transform group-open:rotate-180" /></summary><p className="mt-3 max-w-2xl text-xs leading-6 text-muted-foreground">{item.a}</p></details>)}</div>
        </div>
      </section>

      <section className="mx-auto max-w-[1240px] px-5 py-16 sm:px-8 lg:px-10 lg:py-20"><div className="relative overflow-hidden rounded-[28px] bg-[#665ce0] px-6 py-12 text-center text-white sm:px-12 sm:py-16"><div className="absolute -right-10 -top-16 h-64 w-64 rounded-full border border-white/10" /><div className="absolute -right-2 -top-8 h-48 w-48 rounded-full border border-white/10" /><span className="relative mx-auto flex h-11 w-11 items-center justify-center rounded-2xl bg-white/15"><Zap className="h-5 w-5" /></span><h2 className="relative mx-auto mt-5 max-w-2xl text-balance text-[30px] font-semibold leading-tight tracking-[-.045em] sm:text-[40px]">Take a look around. Everything here is safe to click.</h2><p className="relative mx-auto mt-3 max-w-xl text-sm leading-6 text-white/80">Explore the inbox, domain wizard, contacts, analytics, and settings in a local-only frontend preview.</p><Link href="/app" className="relative mt-7 inline-flex h-11 items-center gap-2 rounded-xl bg-white px-5 text-sm font-semibold text-[#39328a] shadow-soft transition hover:-translate-y-0.5">Open the demo workspace<ArrowRight className="h-4 w-4" /></Link><p className="relative mt-3 text-[10px] text-white/65">No real sign-in · No live DNS · No email delivery</p></div></section>

      <footer className="border-t border-border bg-card/60"><div className="mx-auto flex max-w-[1240px] flex-col gap-8 px-5 py-9 sm:px-8 md:flex-row md:items-center md:justify-between lg:px-10"><div><Brand /><p className="mt-3 max-w-xs text-[10px] leading-5 text-muted-foreground">An original frontend demo inspired by the open-source Mailflare project. Not affiliated with its maintainers.</p></div><div className="flex flex-wrap gap-x-6 gap-y-3 text-[11px] font-medium text-muted-foreground"><Link href="/app" className="hover:text-foreground">Demo workspace</Link><Link href="/privacy" className="hover:text-foreground">Privacy</Link><Link href="/terms" className="hover:text-foreground">Terms</Link><Link href="https://github.com/hieunc229/mailflare" target="_blank" rel="noreferrer" className="hover:text-foreground">GitHub <ArrowUpRight className="ml-0.5 inline h-3 w-3" /></Link></div><span className="text-[10px] text-muted-foreground">© 2026 · Frontend preview</span></div></footer>
    </main>
  );
}

function TrustItem({ icon: Icon, title, detail }: { icon: typeof Globe2; title: string; detail: string }) {
  return <div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-xl border border-border bg-background text-primary"><Icon className="h-4 w-4" /></span><div><p className="text-xs font-semibold">{title}</p><p className="mt-0.5 text-[10px] text-muted-foreground">{detail}</p></div></div>;
}

function BadgeLike({ children }: { children: React.ReactNode }) {
  return <span className="rounded-full bg-muted px-2.5 py-1 text-[9px] font-bold tracking-[.1em] text-muted-foreground">{children}</span>;
}

function ProductPreview() {
  const demoRows = [
    { initials: "MC", name: "Maya Chen", subject: "The brand direction looks wonderful", preview: "Thanks for sharing the updated concepts…", time: "9:42 AM", unread: true, color: "bg-violet-500/15 text-violet-700" },
    { initials: "NP", name: "Noah Patel", subject: "Re: project timeline", preview: "Perfect, that gives our team enough time…", time: "8:16 AM", unread: true, color: "bg-sky-500/15 text-sky-700" },
    { initials: "LO", name: "Lena Ortiz", subject: "A few ideas for fall", preview: "I pulled together a short list of stories…", time: "Yesterday", unread: false, color: "bg-amber-500/15 text-amber-700" },
  ];
  return <div className="relative mx-auto w-full max-w-[640px] animate-fade-up lg:ml-auto">
    <div className="absolute -left-8 top-20 h-28 w-28 rounded-full bg-violet-300/25 blur-3xl" /><div className="absolute -right-8 bottom-16 h-32 w-32 rounded-full bg-sky-300/30 blur-3xl" />
    <div className="relative rotate-[.5deg] rounded-[22px] border border-border/80 bg-card p-2 shadow-[0_30px_100px_rgba(38,40,82,.18)] sm:p-3">
      <div className="flex h-8 items-center gap-1.5 border-b border-border px-2 pb-2"><i className="h-2 w-2 rounded-full bg-rose-400" /><i className="h-2 w-2 rounded-full bg-amber-400" /><i className="h-2 w-2 rounded-full bg-emerald-400" /><span className="ml-3 flex h-5 flex-1 items-center justify-center rounded-md bg-muted text-[8px] text-muted-foreground">app.mailflare.local / inbox</span></div>
      <div className="flex h-[360px] overflow-hidden rounded-b-[15px] sm:h-[425px]">
        <div className="hidden w-[135px] shrink-0 border-r border-border bg-muted/15 p-3 sm:block"><div className="mb-4 flex items-center gap-1.5"><span className="flex h-5 w-5 items-center justify-center rounded-md bg-primary text-white"><Mail className="h-3 w-3" /></span><span className="text-[9px] font-bold">mailflare</span></div><div className="mb-3 rounded-md border border-border bg-card px-2 py-1.5 text-[7px] font-medium text-muted-foreground">Northstar Studio</div><div className="space-y-1">{[{ label: "Overview", icon: BarChart3 }, { label: "Inbox", icon: Inbox, active: true }, { label: "Sent", icon: ArrowUpRight }, { label: "Domains", icon: Globe2 }, { label: "Contacts", icon: ContactRound }].map(({ label, icon: Icon, active }) => <div key={label} className={`flex items-center gap-2 rounded-md px-2 py-1.5 text-[8px] ${active ? "bg-primary/10 font-semibold text-primary" : "text-muted-foreground"}`}><Icon className="h-3 w-3" />{label}{label === "Inbox" && <span className="ml-auto text-[7px]">2</span>}</div>)}</div><div className="mt-7 rounded-lg border border-border bg-card p-2"><p className="text-[7px] font-semibold">Domain status</p><p className="mt-1 text-[7px] text-muted-foreground">northstar.studio</p><div className="mt-2 flex items-center gap-1 text-[7px] text-emerald-600"><i className="h-1.5 w-1.5 rounded-full bg-emerald-500" />Ready</div></div></div>
        <div className="flex min-w-0 flex-1 flex-col bg-card"><div className="flex h-10 items-center justify-between border-b border-border px-3 sm:px-4"><div><p className="text-[10px] font-semibold">Inbox <span className="ml-1 text-[8px] font-normal text-muted-foreground">(2 unread)</span></p></div><div className="flex items-center gap-1.5"><span className="hidden h-6 w-28 items-center gap-1 rounded-md bg-muted px-2 text-[7px] text-muted-foreground sm:flex"><Mail className="h-2.5 w-2.5" />Search mail…</span><span className="flex h-6 w-6 items-center justify-center rounded-md border border-border"><Sparkles className="h-3 w-3 text-primary" /></span><span className="flex h-6 w-6 items-center justify-center rounded-md bg-violet-500 text-[7px] font-bold text-white">AM</span></div></div>
          <div className="flex items-center gap-2 border-b border-border px-3 py-2 sm:px-4"><span className="h-3 w-3 rounded border border-muted-foreground/40" /><span className="flex items-center gap-1 rounded-md bg-muted px-2 py-1 text-[7px] font-medium text-muted-foreground">All messages<ChevronDown className="h-2.5 w-2.5" /></span><span className="ml-auto text-[7px] text-muted-foreground">Showing 1–6 of 6</span></div>
          <div className="divide-y divide-border">{demoRows.map((row) => <div key={row.name} className={`flex min-h-[67px] items-center gap-2 px-3 py-2 sm:gap-2.5 sm:px-4 ${row.unread ? "bg-primary/[.025]" : ""}`}><span className="h-3 w-3 rounded border border-muted-foreground/35" /><span className={`flex h-7 w-7 shrink-0 items-center justify-center rounded-full text-[8px] font-bold ${row.color}`}>{row.initials}</span><span className="min-w-0 flex-1"><span className="flex items-center gap-1"><span className={`truncate text-[8px] ${row.unread ? "font-bold" : "font-medium"}`}>{row.name}</span>{row.unread && <i className="h-1 w-1 rounded-full bg-primary" />}</span><span className="mt-1 block truncate text-[8px] font-semibold">{row.subject}</span><span className="mt-0.5 hidden truncate text-[7px] text-muted-foreground sm:block">{row.preview}</span></span><span className="shrink-0 self-start pt-1 text-[7px] text-muted-foreground">{row.time}</span></div>)}</div>
          <div className="mt-auto border-t border-border bg-muted/15 px-4 py-3"><div className="flex items-center justify-between"><p className="text-[8px] font-semibold">Last 7 days <span className="font-normal text-muted-foreground">· demo data</span></p><span className="flex items-center gap-2 text-[7px] text-muted-foreground"><i className="h-1.5 w-1.5 rounded-full bg-primary" />Received <i className="h-1.5 w-1.5 rounded-full bg-sky-400" />Sent demo</span></div><svg viewBox="0 0 520 70" className="mt-2 h-12 w-full" aria-label="Illustrative email activity chart"><path d="M0 57 C20 54, 29 33, 54 37 S88 60, 108 48 S142 28, 162 39 S191 50, 210 34 S239 44, 261 29 S293 50, 318 36 S348 16, 372 28 S405 48, 428 33 S460 20, 485 24 S505 15, 520 11" fill="none" stroke="#7165df" strokeWidth="2.5" /><path d="M0 64 C25 60,32 55,55 58 S93 43,110 52 S140 60,164 52 S190 40,210 47 S245 52,262 44 S300 51,320 42 S348 40,372 44 S402 52,428 43 S461 48,484 39 S507 37,520 33" fill="none" stroke="#38bdf8" strokeWidth="2" opacity=".85" /><path d="M0 70 H520" stroke="hsl(var(--border))" /></svg></div>
        </div>
      </div>
    </div>
    <div className="absolute -bottom-5 -left-4 hidden items-center gap-2 rounded-2xl border border-border bg-card px-3 py-2.5 shadow-soft sm:flex"><span className="flex h-7 w-7 items-center justify-center rounded-lg bg-emerald-500/10 text-emerald-600"><Check className="h-4 w-4" /></span><span><span className="block text-[9px] font-semibold">Domain ready</span><span className="mt-0.5 block text-[8px] text-muted-foreground">northstar.studio</span></span></div>
    <div className="absolute -right-4 top-10 hidden items-center gap-2 rounded-2xl border border-border bg-card px-3 py-2.5 shadow-soft md:flex"><span className="flex h-7 w-7 items-center justify-center rounded-lg bg-primary/10 text-primary"><Zap className="h-4 w-4" /></span><span><span className="block text-[9px] font-semibold">Tidy by design</span><span className="mt-0.5 block text-[8px] text-muted-foreground">One inbox, your domain</span></span></div>
  </div>;
}
